name: lualaba_konnect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  dotted_border: ^3.1.0
  image_picker: ^1.2.1
  file_picker: ^10.3.8
  intl: ^0.19.0
  geolocator: ^13.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.2.5
  syncfusion_flutter_pdf: ^28.1.33
  google_mlkit_text_recognition: ^0.11.0
  pdfx: ^2.4.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#012E32"
  adaptive_icon_foreground: "assets/logo.png"