name: lualaba_konnect
description: "A new Flutter project for Lualaba Konnect."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Utils
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0           # <--- GARDÃ‰ ICI
  dotted_border: ^3.1.0
  url_launcher: ^6.2.5
  timeago: ^3.7.0
  
  

  # Storage & Media
  image_picker: ^1.2.1
  file_picker: ^8.1.7
  photo_manager: ^3.3.0
  video_player: ^2.8.1
  shared_preferences: ^2.5.4
  record: ^5.1.0
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  camera: ^0.11.0
  emoji_picker_flutter: ^3.0.0
  # intl: ^0.19.0         # <--- SUPPRIMÃ‰ ICI (C'Ã‰TAIT LE DOUBLON)

  # PDF & OCR
  syncfusion_flutter_pdf: ^28.1.33
  pdfx: ^2.4.0
  google_mlkit_text_recognition: ^0.11.0

  # Location & Sensors
  geolocator: ^13.0.0
  geocoding: ^3.0.0
  sensors_plus: ^6.1.1

  # Notifications
  flutter_local_notifications: ^17.2.1

  # AI & Network
  google_generative_ai: ^0.4.7
  http: ^1.1.0

  # ðŸ”¥ FIREBASE
  firebase_core: ^3.15.2
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#f26522"
  adaptive_icon_foreground: "assets/logo.png"